// <auto-generated />
using System;
using Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20260204232746_AddRentalStatusHistory")]
    partial class AddRentalStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Common.Entities.CarCategory", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CarCategory");
                });

            modelBuilder.Entity("Common.Entities.CarFeature", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CarFeature");
                });

            modelBuilder.Entity("Common.Entities.CarLocation", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("CarLocation");
                });

            modelBuilder.Entity("Common.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Convertible"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Minivan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pickup Truck"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wagon"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Limousine"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gasoline"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Hybrid"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Automatic"
                        });
                });

            modelBuilder.Entity("Common.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GPS Navigation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bluetooth Connectivity"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Heated Seats"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sunroof"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Backup Camera"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cruise Control"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Keyless Entry"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Alloy Wheels"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Premium Sound System"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Leather Seats"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Parking Sensors"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Remote Start"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Wi-Fi Hotspot"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Voice Control"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Automatic Emergency Braking"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Lane Departure Warning"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Blind Spot Monitoring"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Adaptive Cruise Control"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Tire Pressure Monitoring System"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Fog Lights"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Roof Rails"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Third-Row Seating"
                        },
                        new
                        {
                            Id = 24,
                            Name = "All-Wheel Drive"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Lane Assist"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Traffic Sign Recognition"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Head-Up Display"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Night Vision Assist"
                        },
                        new
                        {
                            Id = 29,
                            Name = "360-Degree Camera System"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Electric Vehicle Charging Port"
                        });
                });

            modelBuilder.Entity("Common.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Common.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Common.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("PickupLocationId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnLocationId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("ReturnLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Common.Entities.RentalStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("RentalStatusHistories");
                });

            modelBuilder.Entity("Common.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Employer"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("Common.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admin",
                            LastName = "Adminov",
                            Password = "admin123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Common.Entities.UserRoles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Common.Entities.CarCategory", b =>
                {
                    b.HasOne("Common.Entities.Car", "Car")
                        .WithMany("CarCategories")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Entities.Category", "Category")
                        .WithMany("CarCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Common.Entities.CarFeature", b =>
                {
                    b.HasOne("Common.Entities.Car", "Car")
                        .WithMany("CarFeatures")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Entities.Feature", "Feature")
                        .WithMany("CarFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Common.Entities.CarLocation", b =>
                {
                    b.HasOne("Common.Entities.Car", "Car")
                        .WithMany("CarLocations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Entities.Location", "Location")
                        .WithMany("CarLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Common.Entities.Payment", b =>
                {
                    b.HasOne("Common.Entities.Rental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("Common.Entities.Rental", b =>
                {
                    b.HasOne("Common.Entities.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Entities.Location", "PickupLocation")
                        .WithMany("PickupRentals")
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Entities.Location", "ReturnLocation")
                        .WithMany("ReturnRentals")
                        .HasForeignKey("ReturnLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Entities.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("PickupLocation");

                    b.Navigation("ReturnLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Entities.RentalStatusHistory", b =>
                {
                    b.HasOne("Common.Entities.Rental", "Rental")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("Common.Entities.UserRoles", b =>
                {
                    b.HasOne("Common.Entities.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Entities.Car", b =>
                {
                    b.Navigation("CarCategories");

                    b.Navigation("CarFeatures");

                    b.Navigation("CarLocations");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Common.Entities.Category", b =>
                {
                    b.Navigation("CarCategories");
                });

            modelBuilder.Entity("Common.Entities.Feature", b =>
                {
                    b.Navigation("CarFeatures");
                });

            modelBuilder.Entity("Common.Entities.Location", b =>
                {
                    b.Navigation("CarLocations");

                    b.Navigation("PickupRentals");

                    b.Navigation("ReturnRentals");
                });

            modelBuilder.Entity("Common.Entities.Rental", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Common.Entities.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Common.Entities.User", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
